### ISSUE TITLE
CancellationToken with DataFlow

### ISSUE THREAD

**Issue by LGreenberger** [gridsum/DataflowEx#7]
Hi. With raw TPL you can set a CancellationToken in the ExecutionDataflowBlockOptions of each dataflow block for easy cancellation of an entire network. However, I am not seeing an equivalent feature in your DataFlowEx library. How would you suggest handling/processing cancellation requests using your API? Thanks!

**Comment by aevitas** [comment]
It appears DataflowEx supports registering your `CancellationTokenSource` with a specific dataflow instance. Something along the lines of:

	var cts = new CancellationTokenSource();
	dataflow.RegisterCancellationTokenSource(cts);

This then appears to be added to an `ImmutableList<CancellationTokenSource>`, which all get Cancelled if `GetCompletionTask()` throws an exception. I'm not entirely sure why the choice for multiple sources was made, or how the tokens are being handed out to the underlying dataflows, maybe that's something one of the authors can answer. :)

**Comment by karldodd** [comment]
@LGreenberger DataflowEx doesn't stop you from using explicit ExecutionDataflowBlockOptions with cancellation token. You can still use low-level TPL Dataflow api to construct the **block** you want and then call `RegisterChild` in the ctor of your Dataflow class.

@aevitas Thanks for joining the discussion. The documentation of `RegisterCancellationTokenSource()` says:

```
Register a cancellation token source which will be signaled to external components 
if this dataflow runs into error. (Useful to terminate input stream to the dataflow
together with PullFromAsync)
```

RegisterCancellationTokenSource is used to signal cancellation from inside **this** dataflow to **external** components (e.g. an upstream dataflow so that it stops sending messages to this dataflow). So this function is different from cancellation token in ExecutionDataflowBlockOptions, which is primarily allowing external cancellation signal to affect a block. Just different use cases (different signal directions).

**Comment by karldodd** [comment]
Close as 'answered'.
